### ISSUE TITLE
InterceptorChain.kt line 26

### ISSUE THREAD

**Issue by amineghabi** [B3nedikt/ViewPump#25]
Caused by android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f08018e
       at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:273)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:732)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:616)
       at android.content.res.Resources.loadDrawable(Resources.java:858)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
       at android.widget.ImageView.<init>(ImageView.java:162)
       at android.widget.ImageView.<init>(ImageView.java:150)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:74)
       at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:69)
       at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:199)
       at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:119)
       at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1563)
       at androidx.appcompat.app.AppCompatDelegateWrapper.createView(AppCompatDelegateWrapper.kt:129)
       at androidx.appcompat.app.ViewPumpAppCompatDelegate.access$createView$s1741359083(ViewPumpAppCompatDelegate.kt:29)
       at androidx.appcompat.app.ViewPumpAppCompatDelegate$createView$1.invoke(ViewPumpAppCompatDelegate.kt:69)
       at androidx.appcompat.app.ViewPumpAppCompatDelegate$createView$1.invoke(ViewPumpAppCompatDelegate.kt:55)
       **at dev.b3nedikt.viewpump.internal.InterceptorChain.proceed(InterceptorChain.kt:26)
       at dev.b3nedikt.reword.RewordInterceptor.intercept(RewordInterceptor.kt:14)
       at dev.b3nedikt.viewpump.internal.InterceptorChain.proceed(InterceptorChain.kt:37)
       at androidx.appcompat.app.ViewPumpAppCompatDelegate.inflate(ViewPumpAppCompatDelegate.kt:120)
       at androidx.appcompat.app.ViewPumpAppCompatDelegate.createView(ViewPumpAppCompatDelegate.kt:55)
       at androidx.appcompat.app.ViewPumpAppCompatDelegate.onCreateView(ViewPumpAppCompatDelegate.kt:106)**
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
       at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1409)
       at OnboardingBinding.inflate(ActivityOnboardingBinding.java:145)
       at OnboardingBinding.inflate(ActivityOnboardingBinding.java:131)
       at OnboardingActivity.onCreate(OnboardingActivity.java:56)
       at android.app.Activity.performCreate(Activity.java:6785)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by B3nedikt** [comment]
I need more info on this to help ;) Please fork this repository and try to recreate the exception in the sample app of this repository, then link your fork to this issue.
